Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

pizzas/urls.py
from django.urls import path
from . import views


app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'), #homepage
    path('pizzas',views.pizzas,name='pizzas'), #page with different pizzas
    path('pizza/<int:pizza_id>/',views.pizza,name='pizza'), #a selected pizza
    #path('new_pizza',views.new_pizza,name='new_pizza'),
    path('comments/pizza',views.comments,name='comments'), # the page to make comments on the pizza

]

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)

    
        
    def __str__(self):
        return self.topping_name


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comments = models.TextField()

    def __str__(self):
        return self.comments

pizzas/forms.py
from django import forms

from .models import * 
'''
class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['pizza_name']
        labels = {'pizza_name':'Pizza Name'}
'''
'''
class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['topping_name']
        labels = {'topping_name':''}

        widgets = {'topping_name': forms.Textarea(attrs={'cols':80})}


'''

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comments']
        labels = {'comments':''}

        widgets = {'comments': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')



def pizzas(request):
    pizzas = Pizza.objects.order_by()

    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=pizza)
    comments = Comment.objects.filter(pizza=pizza)

    context = {'pizza':pizza, 'toppings':toppings}

    return render(request, 'pizzas/pizza.html',context)

'''
def new_pizza(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        print(request.POST)
        form = PizzaForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizzas')

    context = {'form':form}
    return render(request, 'pizzas/new_pizza.html',context)
'''

'''
def new_topping(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = ToppingForm()
    else:
        print(request.POST)
        form = ToppingForm(data=request.POST)
        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form,'pizza':pizza}
    return render(request, 'pizzas/new_topping.html',context)
    '''

def comments(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentsForm()
    else:
        print(request.POST)
        form = CommentsForm(data=request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.pizza = pizza
            comments.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form,'pizza':pizza}
    return render(request, 'pizzas/comments.html',context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizza Home Page</a>
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>






</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a></p>

<p>Add a New comment</p>



<form action="{% url 'pizzas:comments' pizza.id %}" method="post">

    {% csrf_token %} 

    {{ form.as_p }}

    <button name="Submit">Add Comment</button>

    
</form>


{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %} 

{% block content %} 

<p>
    This is the homepage
</p>

{% endblock content %} 

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza: {{ pizza }}</p>
<P>Toppings:</P>
<ul>

    {% for t in toppings %}
    <li>{{ t.topping_name }}</li>
    
    
    {% empty %}
    <li>No toppings for this pizza have been added yet.</li>
    {% endfor %}
</ul>

<p>Comments: </p>
<ul>
    {% for c in comments %} 
    <li>{{ c.comments }}</li>

    {% empty %} 
    <li>No comments have been made on this pizza yet.</li>
    {% endfor %} 


</ul>



<p>
    <a href="{% url 'pizzas:comments' pizza.id %}">Add a new comment</a>
</p>


{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>

    {% for p in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' p.id %}">{{p}}</a>
        </li>

    {% endfor %}
</ul>


{% endblock content %}